### ISSUE TITLE
Home page URL redirected to / when redirect module enabled in Drupal 8.0.0-beta15

### ISSUE THREAD

**Issue by nhero** [md-systems/redirect#55]
I have a fresh Drupal 8 beta 15 install with one node on it with a path of localhost/test-article which can be accessed at both localhost/test-article and localhost/ however, once the redirect module is enabled localhost/test-article gets redirected to localhost/. Disabling the module makes both paths available. This appears to only be happening to the node set to the home page.

**Comment by Berdir** [comment]
This is by design and a feature (previously part of globalredirect). The same content shouldn't be available on different URL's, google doesn't like that and it's weird if the frontpage is reachable under some other URL as users might end up there.

Anyway, it's also a configurable feature, if you don't like it, just disable it in the settings.
